### ISSUE TITLE
Calling an action vs Dispatcher.dispatch

### ISSUE THREAD

**Issue by coniel** [MeteorFlux/CartFlux#1]
I'm a little confused about the purpose of actions. It seems like the only place you use them is for user actions. Why not have the login action code in the UserStore and do something like Dispatcher.dispatch({ actionType: "LOGIN_FORM_SUBMISSION", credentials: {...} });

Is there a particular reason for actions?

**Comment by luisherranz** [comment]
Facebook people recommend to use actions for async methods because the "one-way-data-flow" should be always synchronous. Your action receiving the callback from the async method is the one which starts a new sync "one-way-data-flow" with the result.

You can define actions for synchronous operations as well, but it is optional.

**Comment by coniel** [comment]
@LuisHerranz Thanks a lot! I get it now.

**Comment by luisherranz** [comment]
No problem :)
